name = input('Enter your name: ')
age = int(input('Enter your age: '))
city = input('Enter the city you are from: ')
greeting_1 = 'Hello %s from %s aged %d'% (name, city, age)
print(greeting_1)

name = input('Enter your name: ')
age = int(input('Enter your age: '))
city = input('Enter the city you are from: ')
greeting_2 = 'Hello {} from {} aged {}'.format(name, city, age)
print(greeting_2)