CREATE TABLE IF NOT EXISTS order_items(
id SMALLSERIAL PRIMARY KEY,
order_id SMALLSERIAL NOT NULL,
FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
product_id SMALLINT NOT NULL,
FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
total INT);